/**
 * Manufacturer registry for electric scooter brands.
 * Each manufacturer has product listing URLs that can be scanned
 * by the discovery system to find new scooter models.
 */

export interface Manufacturer {
	id: string;
	name: string;
	website: string;
	/** URLs to scan for product listings (collection pages, product catalogs) */
	productListingUrls: string[];
	/** Scooter keys in our system that belong to this manufacturer */
	knownScooterKeys: string[];
	/** Whether the site serves static HTML (scrapable) or is JS-rendered */
	scrapable: boolean;
	country: string;
	/** Price tier: budget (<$500), mid ($500-$1500), premium ($1500-$3000), ultra (>$3000) */
	tier: 'budget' | 'mid' | 'premium' | 'ultra' | 'mixed';
}

export const manufacturers: Manufacturer[] = [
	{
		id: 'apollo',
		name: 'Apollo Scooters',
		website: 'https://apolloscooters.com',
		productListingUrls: ['https://apolloscooters.com/collections/electric-scooters'],
		knownScooterKeys: ['apollo_city_2024_pro', 'apollo_go'],
		scrapable: false, // JS-rendered
		country: 'Canada',
		tier: 'mid',
	},
	{
		id: 'segway',
		name: 'Segway-Ninebot',
		website: 'https://store.segway.com',
		productListingUrls: ['https://store.segway.com/ekickscooter', 'https://store.segway.com'],
		knownScooterKeys: ['segway_e2_pro', 'segway_gt1', 'segway_gt2', 'segway_max_g2'],
		scrapable: true,
		country: 'China',
		tier: 'mixed',
	},
	{
		id: 'kaabo',
		name: 'Kaabo',
		website: 'https://www.kaabo.com',
		productListingUrls: ['https://www.voromotors.com/collections/kaabo', 'https://fluidfreeride.com/collections/kaabo'],
		knownScooterKeys: ['wolf_king_gtr', 'kaabo_mantis_king_gt'],
		scrapable: true,
		country: 'China',
		tier: 'premium',
	},
	{
		id: 'emove',
		name: 'EMOVE (Voro Motors)',
		website: 'https://www.voromotors.com',
		productListingUrls: [
			'https://www.voromotors.com/collections/emove-electric-scooters',
			'https://www.voromotors.com/collections/all',
		],
		knownScooterKeys: ['emove_roadster', 'emove_cruiser_s'],
		scrapable: true,
		country: 'USA',
		tier: 'mixed',
	},
	{
		id: 'nami',
		name: 'NAMI Electric',
		website: 'https://www.namiscooters.com',
		productListingUrls: ['https://fluidfreeride.com/collections/nami', 'https://www.voromotors.com/collections/nami'],
		knownScooterKeys: ['nami_klima', 'nami_burn_e_2_max'],
		scrapable: true,
		country: 'South Korea',
		tier: 'ultra',
	},
	{
		id: 'vsett',
		name: 'VSETT',
		website: 'https://vsett.com',
		productListingUrls: ['https://revrides.com/collections/vsett', 'https://fluidfreeride.com/collections/vsett'],
		knownScooterKeys: ['vsett_10_plus', 'vsett_9_plus', 'vsett_8'],
		scrapable: true,
		country: 'China',
		tier: 'mid',
	},
	{
		id: 'xiaomi',
		name: 'Xiaomi',
		website: 'https://www.mi.com',
		productListingUrls: ['https://www.mi.com/global/product/electric-scooter'],
		knownScooterKeys: ['xiaomi_4_lite_2', 'xiaomi_4_ultra', 'm365_pro_2'],
		scrapable: false, // JS-rendered
		country: 'China',
		tier: 'budget',
	},
	{
		id: 'niu',
		name: 'NIU',
		website: 'https://global.niu.com',
		productListingUrls: ['https://global.niu.com/product'],
		knownScooterKeys: ['niu_kqi_air', 'niu_kqi3_max', 'niu_kqi2_pro'],
		scrapable: true,
		country: 'China',
		tier: 'mid',
	},
	{
		id: 'gotrax',
		name: 'Gotrax',
		website: 'https://gotrax.com',
		productListingUrls: ['https://gotrax.com/collections/electric-scooters'],
		knownScooterKeys: ['gotrax_g4'],
		scrapable: true,
		country: 'USA',
		tier: 'budget',
	},
	{
		id: 'hiboy',
		name: 'Hiboy',
		website: 'https://www.hiboy.com',
		productListingUrls: ['https://www.hiboy.com/collections/electric-scooter'],
		knownScooterKeys: ['hiboy_s2_pro'],
		scrapable: true,
		country: 'China',
		tier: 'budget',
	},
	{
		id: 'dualtron',
		name: 'Dualtron (MiniMotors)',
		website: 'https://www.minimotorsusa.com',
		productListingUrls: ['https://www.voromotors.com/collections/dualtron'],
		knownScooterKeys: ['dualtron_thunder_3'],
		scrapable: true,
		country: 'South Korea',
		tier: 'ultra',
	},
	{
		id: 'inmotion',
		name: 'InMotion',
		website: 'https://www.inmotionworld.com',
		productListingUrls: ['https://fluidfreeride.com/collections/inmotion'],
		knownScooterKeys: ['inmotion_rs'],
		scrapable: true,
		country: 'China',
		tier: 'premium',
	},
	{
		id: 'teverun',
		name: 'Teverun',
		website: 'https://teverun.com',
		productListingUrls: ['https://www.voromotors.com/collections/teverun'],
		knownScooterKeys: ['teverun_fighter_supreme'],
		scrapable: true,
		country: 'China',
		tier: 'ultra',
	},
	{
		id: 'unagi',
		name: 'Unagi',
		website: 'https://unagiscooters.com',
		productListingUrls: ['https://unagiscooters.com/collections/all'],
		knownScooterKeys: ['unagi_voyager'],
		scrapable: true,
		country: 'USA',
		tier: 'mid',
	},
	{
		id: 'inokim',
		name: 'Inokim',
		website: 'https://www.inokim.com',
		productListingUrls: ['https://www.inokim.com/product-category/electric-scooters/'],
		knownScooterKeys: ['inokim_light_2'],
		scrapable: true,
		country: 'Israel',
		tier: 'mid',
	},
	{
		id: 'navee',
		name: 'NAVEE',
		website: 'https://www.naveetech.com',
		productListingUrls: ['https://www.naveetech.com'],
		knownScooterKeys: ['navee_gt3'],
		scrapable: true,
		country: 'China',
		tier: 'budget',
	},
	{
		id: 'varla',
		name: 'Varla Scooter',
		website: 'https://varlascooter.com',
		productListingUrls: ['https://varlascooter.com/collections/electric-scooters'],
		knownScooterKeys: [],
		scrapable: true,
		country: 'USA',
		tier: 'mid',
	},
	{
		id: 'zero',
		name: 'ZERO Scooters',
		website: 'https://zeroscooters.com',
		productListingUrls: ['https://revrides.com/collections/zero', 'https://www.voromotors.com/collections/zero'],
		knownScooterKeys: [],
		scrapable: true,
		country: 'China',
		tier: 'premium',
	},
	{
		id: 'blade',
		name: 'Blade Scooters',
		website: 'https://bladescooters.com',
		productListingUrls: ['https://www.voromotors.com/collections/blade'],
		knownScooterKeys: [],
		scrapable: true,
		country: 'China',
		tier: 'premium',
	},
	{
		id: 'mercane',
		name: 'Mercane',
		website: 'https://www.mercane.com',
		productListingUrls: ['https://fluidfreeride.com/collections/mercane'],
		knownScooterKeys: [],
		scrapable: true,
		country: 'China',
		tier: 'mid',
	},
	{
		id: 'turboant',
		name: 'TurboAnt',
		website: 'https://www.isinwheel.com',
		productListingUrls: ['https://www.isinwheel.com/collections/electric-scooters'],
		knownScooterKeys: ['turboant_x7_max'],
		scrapable: true,
		country: 'China',
		tier: 'budget',
	},
	{
		id: 'levy',
		name: 'Levy Electric',
		website: 'https://www.levyelectric.com',
		productListingUrls: ['https://www.levyelectric.com/collections/all'],
		knownScooterKeys: [],
		scrapable: true,
		country: 'USA',
		tier: 'budget',
	},
	{
		id: 'pure',
		name: 'Pure Electric',
		website: 'https://www.pureelectric.com',
		productListingUrls: ['https://www.pureelectric.com/collections/electric-scooters'],
		knownScooterKeys: [],
		scrapable: true,
		country: 'UK',
		tier: 'mid',
	},
	{
		id: 'uscooters',
		name: 'UScooters (E-TWOW)',
		website: 'https://uscooters.com',
		productListingUrls: ['https://uscooters.com/collections/all'],
		knownScooterKeys: ['uscooters_gt_sport'],
		scrapable: true,
		country: 'Romania',
		tier: 'mid',
	},
	{
		id: 'mukuta',
		name: 'Mukuta',
		website: 'https://mukuta.com',
		productListingUrls: ['https://www.voromotors.com/collections/mukuta'],
		knownScooterKeys: ['mukuta_10_plus'],
		scrapable: true,
		country: 'China',
		tier: 'premium',
	},
	{
		id: 'roadrunner',
		name: 'RoadRunner Scooters',
		website: 'https://roadrunnerscooters.com',
		productListingUrls: ['https://roadrunnerscooters.com/collections/all'],
		knownScooterKeys: ['roadrunner_rs5_plus'],
		scrapable: true,
		country: 'USA',
		tier: 'premium',
	},
	{
		id: 'wolf_warrior',
		name: 'Wolf Warrior (Kaabo)',
		website: 'https://www.wolfwarriorscooters.com',
		productListingUrls: ['https://www.voromotors.com/collections/wolf-warrior'],
		knownScooterKeys: [],
		scrapable: true,
		country: 'China',
		tier: 'ultra',
	},
	{
		id: 'evercross',
		name: 'EVERCROSS',
		website: 'https://www.evercross.com',
		productListingUrls: ['https://www.evercross.com/collections/e-scooter'],
		knownScooterKeys: [],
		scrapable: true,
		country: 'China',
		tier: 'budget',
	},
	{
		id: 'nanrobot',
		name: 'Nanrobot',
		website: 'https://www.nanrobot.com',
		productListingUrls: ['https://www.nanrobot.com/collections/electric-scooter'],
		knownScooterKeys: [],
		scrapable: true,
		country: 'China',
		tier: 'mid',
	},
	{
		id: 'joyor',
		name: 'Joyor',
		website: 'https://joyorscooter.com',
		productListingUrls: ['https://joyorscooter.com/product-category/electric-scooter/'],
		knownScooterKeys: [],
		scrapable: true,
		country: 'China',
		tier: 'budget',
	},
	{
		id: 'yume',
		name: 'YUME Scooters',
		website: 'https://yumescooter.com',
		productListingUrls: ['https://yumescooter.com/collections/all'],
		knownScooterKeys: [],
		scrapable: true,
		country: 'China',
		tier: 'mid',
	},
	// --- Missing major brands ---
	{
		id: 'weped',
		name: 'Weped',
		website: 'https://www.weped.com',
		productListingUrls: ['https://fluidfreeride.com/collections/weped', 'https://www.voromotors.com/collections/weped'],
		knownScooterKeys: [],
		scrapable: true,
		country: 'South Korea',
		tier: 'ultra',
	},
	{
		id: 'currus',
		name: 'Currus',
		website: 'https://currus.eu',
		productListingUrls: ['https://fluidfreeride.com/collections/currus', 'https://revrides.com/collections/currus'],
		knownScooterKeys: [],
		scrapable: true,
		country: 'Belgium',
		tier: 'premium',
	},
	{
		id: 'speedway',
		name: 'Speedway (MiniMotors)',
		website: 'https://www.minimotorsusa.com',
		productListingUrls: [
			'https://www.voromotors.com/collections/speedway',
			'https://fluidfreeride.com/collections/speedway',
		],
		knownScooterKeys: [],
		scrapable: true,
		country: 'South Korea',
		tier: 'premium',
	},
	{
		id: 'razor',
		name: 'Razor',
		website: 'https://www.razor.com',
		productListingUrls: ['https://www.razor.com/collections/electric-scooters'],
		knownScooterKeys: [],
		scrapable: true,
		country: 'USA',
		tier: 'budget',
	},
	{
		id: 'hover1',
		name: 'Hover-1',
		website: 'https://www.hover-1.com',
		productListingUrls: ['https://www.hover-1.com/collections/electric-scooters'],
		knownScooterKeys: [],
		scrapable: true,
		country: 'USA',
		tier: 'budget',
	},
	{
		id: 'kugoo',
		name: 'Kugoo',
		website: 'https://kugooescooter.com',
		productListingUrls: ['https://kugooescooter.com/collections/electric-scooter'],
		knownScooterKeys: [],
		scrapable: true,
		country: 'China',
		tier: 'budget',
	},
	{
		id: 'yadea',
		name: 'Yadea',
		website: 'https://www.yadea.com',
		productListingUrls: ['https://www.yadea.com/collections/electric-scooter'],
		knownScooterKeys: [],
		scrapable: true,
		country: 'China',
		tier: 'budget',
	},
	{
		id: 'sxt',
		name: 'SXT Scooters',
		website: 'https://www.sxt-scooters.com',
		productListingUrls: ['https://www.sxt-scooters.com/electric-scooters/'],
		knownScooterKeys: [],
		scrapable: true,
		country: 'Germany',
		tier: 'mid',
	},
	{
		id: 'oxboards',
		name: 'OX Boards',
		website: 'https://oxboards.com',
		productListingUrls: ['https://oxboards.com/collections/electric-scooters'],
		knownScooterKeys: [],
		scrapable: true,
		country: 'China',
		tier: 'ultra',
	},
	{
		id: 'fluid',
		name: 'Fluid FreeRide (own brand)',
		website: 'https://fluidfreeride.com',
		productListingUrls: ['https://fluidfreeride.com/collections/fluid'],
		knownScooterKeys: [],
		scrapable: true,
		country: 'USA',
		tier: 'mid',
	},
	{
		id: 'techlife',
		name: 'Techlife',
		website: 'https://www.techlife-scooter.com',
		productListingUrls: [
			'https://www.techlife-scooter.com/collections/electric-scooter',
			'https://fluidfreeride.com/collections/techlife',
		],
		knownScooterKeys: [],
		scrapable: true,
		country: 'China',
		tier: 'mid',
	},
	{
		id: 'kaabo_usa',
		name: 'Kaabo USA',
		website: 'https://kaaboscooter.com',
		productListingUrls: ['https://kaaboscooter.com/collections/all'],
		knownScooterKeys: [],
		scrapable: true,
		country: 'USA',
		tier: 'premium',
	},
	// --- Retailers (multi-brand, good for discovery) ---
	{
		id: 'fluidfreeride',
		name: 'FluidFreeRide',
		website: 'https://fluidfreeride.com',
		productListingUrls: ['https://fluidfreeride.com/collections/electric-scooters'],
		knownScooterKeys: [],
		scrapable: true,
		country: 'USA',
		tier: 'mixed',
	},
	{
		id: 'voromotors',
		name: 'Voro Motors',
		website: 'https://www.voromotors.com',
		productListingUrls: ['https://www.voromotors.com/collections/electric-scooters'],
		knownScooterKeys: [],
		scrapable: true,
		country: 'USA',
		tier: 'mixed',
	},
	{
		id: 'revrides',
		name: 'RevRides',
		website: 'https://revrides.com',
		productListingUrls: ['https://revrides.com/collections/electric-scooters'],
		knownScooterKeys: [],
		scrapable: true,
		country: 'USA',
		tier: 'mixed',
	},
];

export function getManufacturer(id: string): Manufacturer | undefined {
	return manufacturers.find((m) => m.id === id);
}

export function getManufacturerForScooter(scooterKey: string): Manufacturer | undefined {
	return manufacturers.find((m) => m.knownScooterKeys.includes(scooterKey));
}

export function getScrapableManufacturers(): Manufacturer[] {
	return manufacturers.filter((m) => m.scrapable && m.productListingUrls.length > 0);
}
