/**
 * Programmatically writes approved candidates into presets.ts.
 * When a candidate is approved, its config + metadata are auto-injected.
 * When rejected/deleted, the entry is removed if it was previously added.
 */
import { readFile, writeFile } from 'fs/promises';
import { resolve } from 'path';
import type { PresetCandidate } from './preset-generator';

const PRESETS_PATH = resolve('src/lib/data/presets.ts');

async function readPresetsFile(): Promise<string> {
	return readFile(PRESETS_PATH, 'utf-8');
}

async function writePresetsFile(content: string): Promise<void> {
	return writeFile(PRESETS_PATH, content, 'utf-8');
}

function keyExistsInContent(key: string, content: string): boolean {
	const configPattern = new RegExp(`^\\s*${key}:\\s*\\{`, 'm');
	return configPattern.test(content);
}

export async function isPresetInFile(key: string): Promise<boolean> {
	const content = await readPresetsFile();
	return keyExistsInContent(key, content);
}

/**
 * Add an approved candidate to presets.ts.
 * Inserts config into the `presets` object and metadata into `presetMetadata`.
 */
export async function addPresetToFile(candidate: PresetCandidate): Promise<{ success: boolean; error?: string }> {
	try {
		let content = await readPresetsFile();
		const key = candidate.key;

		// Check existence in already-loaded content (avoids a second file read)
		if (keyExistsInContent(key, content)) {
			return updatePresetInFile(candidate);
		}

		// --- Insert config entry ---
		const configEntry = buildConfigEntry(candidate);
		const metadataEntry = buildMetadataEntry(candidate);

		// Find the "// --- Auto-discovered Models ---" section and insert at the start,
		// or insert just before the closing `};` of the presets object
		const autoGeneratedMarker = '  // --- Auto-discovered Models ---\n';

		if (!content.includes('// --- Auto-discovered Models ---')) {
			// Add the section marker before the closing of presets object
			const defaultConfigIdx = content.indexOf('export const defaultConfig');
			if (defaultConfigIdx === -1) {
				return { success: false, error: 'Could not find preset insertion point' };
			}

			// Find the `};` that closes the presets object (the one right before defaultConfig)
			const beforeDefault = content.slice(0, defaultConfigIdx);
			const lastCloseBrace = beforeDefault.lastIndexOf('};');
			if (lastCloseBrace === -1) {
				return { success: false, error: 'Could not find presets closing brace' };
			}

			// Ensure the previous entry has a trailing comma
			content = ensureTrailingComma(content, lastCloseBrace);

			// Re-find after potential content shift
			const newDefaultIdx = content.indexOf('export const defaultConfig');
			const newBeforeDefault = content.slice(0, newDefaultIdx);
			const newCloseBrace = newBeforeDefault.lastIndexOf('};');

			// Insert the auto-discovered section before the closing `};`
			content =
				content.slice(0, newCloseBrace) +
				'\n' +
				autoGeneratedMarker +
				configEntry +
				'\n' +
				content.slice(newCloseBrace);
		} else {
			// Section exists — insert after the marker
			const markerIdx = content.indexOf('// --- Auto-discovered Models ---');
			const markerLineEnd = content.indexOf('\n', markerIdx) + 1;
			content = content.slice(0, markerLineEnd) + configEntry + '\n' + content.slice(markerLineEnd);
		}

		// --- Insert metadata entry ---
		const metaAutoMarker = '  // --- Auto-discovered Models ---\n';

		// Count how many auto-discovered markers exist (need one in config, one in metadata)
		const firstMarkerIdx = content.indexOf('// --- Auto-discovered Models ---');
		const secondMarkerIdx = content.indexOf('// --- Auto-discovered Models ---', firstMarkerIdx + 1);

		if (secondMarkerIdx === -1) {
			// Need to add a second marker in the metadata section
			// Find the closing `};` of presetMetadata (the very last one in the file)
			const lastSemicolon = content.lastIndexOf('};');
			if (lastSemicolon === -1) {
				return { success: false, error: 'Could not find metadata closing brace' };
			}

			// Ensure trailing comma on previous entry
			content = ensureTrailingComma(content, lastSemicolon);
			const newLastSemicolon = content.lastIndexOf('};');

			content =
				content.slice(0, newLastSemicolon) +
				'\n' +
				metaAutoMarker +
				metadataEntry +
				'\n' +
				content.slice(newLastSemicolon);
		} else {
			// Second marker exists — insert metadata after it
			const firstMarker = content.indexOf('// --- Auto-discovered Models ---');
			const secondMarker = content.indexOf('// --- Auto-discovered Models ---', firstMarker + 1);
			const markerLineEnd = content.indexOf('\n', secondMarker) + 1;
			content = content.slice(0, markerLineEnd) + metadataEntry + '\n' + content.slice(markerLineEnd);
		}

		// Bump catalog version
		content = bumpCatalogVersion(content);

		await writePresetsFile(content);
		return { success: true };
	} catch (e) {
		return { success: false, error: e instanceof Error ? e.message : 'Unknown error' };
	}
}

/**
 * Update an existing preset entry in presets.ts.
 */
export async function updatePresetInFile(candidate: PresetCandidate): Promise<{ success: boolean; error?: string }> {
	try {
		let content = await readPresetsFile();
		const key = candidate.key;

		// Remove old entry first, then add new one
		content = removeEntryFromContent(content, key);
		await writePresetsFile(content);

		// Now add the updated entry
		return addPresetToFile(candidate);
	} catch (e) {
		return { success: false, error: e instanceof Error ? e.message : 'Unknown error' };
	}
}

/**
 * Remove a preset from presets.ts.
 */
export async function removePresetFromFile(key: string): Promise<{ success: boolean; error?: string }> {
	try {
		let content = await readPresetsFile();

		if (!keyExistsInContent(key, content)) {
			return { success: true }; // Nothing to remove
		}

		content = removeEntryFromContent(content, key);
		content = bumpCatalogVersion(content);
		await writePresetsFile(content);
		return { success: true };
	} catch (e) {
		return { success: false, error: e instanceof Error ? e.message : 'Unknown error' };
	}
}

/**
 * Sync all approved candidates to presets.ts.
 * Adds any approved candidates not yet in the file, removes any rejected ones that are.
 */
export async function syncApprovedPresets(): Promise<{
	added: string[];
	skipped: string[];
	removed: string[];
	errors: string[];
}> {
	// Dynamic import to avoid circular deps
	const { getCandidates } = await import('./candidate-store');

	const allCandidates = await getCandidates();
	const added: string[] = [];
	const skipped: string[] = [];
	const removed: string[] = [];
	const errors: string[] = [];

	// Read once for all in-memory existence checks; addPresetToFile/removePresetFromFile
	// do their own reads when they need to write, so this avoids N extra reads for skips.
	let snapshot = await readPresetsFile();
	const autoSectionStart = snapshot.indexOf('// --- Auto-discovered Models ---');

	for (const candidate of allCandidates) {
		if (candidate.status === 'approved') {
			if (keyExistsInContent(candidate.key, snapshot)) {
				skipped.push(candidate.key);
			} else {
				const result = await addPresetToFile(candidate);
				if (result.success) {
					added.push(candidate.key);
					// Refresh snapshot so subsequent iterations see the newly added key
					snapshot = await readPresetsFile();
				} else {
					errors.push(`Failed to add ${candidate.key}: ${result.error}`);
				}
			}
		} else if (candidate.status === 'rejected') {
			// Only remove if it's in the auto-discovered section
			const inAutoSection = autoSectionStart !== -1 && snapshot.slice(autoSectionStart).includes(`${candidate.key}: {`);
			if (inAutoSection) {
				const result = await removePresetFromFile(candidate.key);
				if (result.success) {
					removed.push(candidate.key);
					snapshot = await readPresetsFile();
				} else {
					errors.push(`Failed to remove ${candidate.key}: ${result.error}`);
				}
			}
		}
	}

	return { added, skipped, removed, errors };
}

// --- Internal helpers ---

/**
 * Validate preset key — must be a safe identifier to prevent code injection
 * when written as an unquoted property name into TypeScript source.
 */
function validatePresetKey(key: string): void {
	if (!/^[a-z][a-z0-9_]{0,49}$/.test(key)) {
		throw new Error(`Invalid preset key "${key}": must match /^[a-z][a-z0-9_]{0,49}$/`);
	}
}

/**
 * Escape a string for safe interpolation inside a double-quoted TS string literal.
 * Handles backslashes, quotes, newlines, carriage returns, tabs and NUL bytes.
 */
function escapeStringLiteral(s: string): string {
	return s
		.replace(/\\/g, '\\\\')
		.replace(/"/g, '\\"')
		.replace(/\n/g, '\\n')
		.replace(/\r/g, '\\r')
		.replace(/\t/g, '\\t')
		.replace(/\0/g, '\\0');
}

/** Build the config entry string for a candidate */
function buildConfigEntry(candidate: PresetCandidate): string {
	validatePresetKey(candidate.key);
	const c = candidate.config;
	const lines = [
		`  ${candidate.key}: {`,
		`    v: ${c.v}, ah: ${c.ah}, watts: ${c.watts}, motors: ${c.motors}, wheel: ${c.wheel},`,
	];

	if (c.motorKv) {
		lines.push(`    motorKv: ${c.motorKv},`);
	}

	if (c.scooterWeight) {
		lines.push(`    scooterWeight: ${c.scooterWeight},`);
	}

	lines.push(
		`    drivetrainEfficiency: ${c.drivetrainEfficiency ?? 0.9}, batterySagPercent: ${c.batterySagPercent ?? 0.08},`,
		`    charger: ${c.charger}, regen: ${c.regen}, cost: ${c.cost},`,
		`    weight: ${c.weight}, style: ${c.style},`,
		`    slope: 0, ridePosition: ${c.ridePosition}, soh: ${c.soh}, ambientTemp: ${c.ambientTemp},`,
		`  },`
	);

	return lines.join('\n');
}

/** Build the metadata entry string for a candidate */
function buildMetadataEntry(candidate: PresetCandidate): string {
	validatePresetKey(candidate.key);
	const m = candidate.manufacturerSpecs;
	const today = new Date().toISOString().slice(0, 10);
	const source = escapeStringLiteral(candidate.sources.discoveredFrom || 'Auto-discovered');

	const mfrFields: string[] = [];
	// topSpeed, range, batteryWh are required in PresetMetadata type — always include them
	mfrFields.push(`topSpeed: ${m.topSpeed || 0}`);
	mfrFields.push(`range: ${m.range || 0}`);
	mfrFields.push(`batteryWh: ${m.batteryWh || 0}`);
	if (m.price) mfrFields.push(`price: ${m.price}`);

	const lines = [
		`  ${candidate.key}: {`,
		`    name: "${escapeStringLiteral(candidate.name)}", year: ${candidate.year},`,
		`    manufacturer: { ${mfrFields.join(', ')} },`,
		`    addedDate: "${today}", lastVerified: "${today}",`,
		`    source: "${source}", status: "current",`,
	];

	if (candidate.notes) {
		lines.push(`    notes: "${escapeStringLiteral(candidate.notes)}",`);
	}

	lines.push(`  },`);
	return lines.join('\n');
}

/**
 * Ensure the last object entry before a given position has a trailing comma.
 * Fixes: `  }\n};` → `  },\n};`
 */
function ensureTrailingComma(content: string, beforePos: number): string {
	// Look backwards from beforePos for the last `}` that isn't followed by `,`
	const before = content.slice(0, beforePos);
	// Find last `}` that is part of an entry (indented with 2 spaces)
	const lastEntryClose = before.lastIndexOf('  }');
	if (lastEntryClose === -1) return content;

	// Check if it already has a comma
	const afterClose = content[lastEntryClose + 3];
	if (afterClose === ',') return content; // Already has comma

	// Insert comma
	return content.slice(0, lastEntryClose + 3) + ',' + content.slice(lastEntryClose + 3);
}

/** Remove a preset key's entries from both config and metadata sections */
function removeEntryFromContent(content: string, key: string): string {
	// Remove config entry: matches `  key: {\n ... \n  },`
	const configRegex = new RegExp(`^  ${key}: \\{[\\s\\S]*?^  \\},?\\n`, 'gm');
	content = content.replace(configRegex, '');

	// Clean up any double blank lines left behind
	content = content.replace(/\n{3,}/g, '\n\n');

	return content;
}

/** Bump the CATALOG_VERSION patch number and update date */
function bumpCatalogVersion(content: string): string {
	const today = new Date().toISOString().slice(0, 10);

	// Bump version
	content = content.replace(
		/CATALOG_VERSION\s*=\s*"(\d+)\.(\d+)\.(\d+)"/,
		(_, major, minor, patch) => `CATALOG_VERSION = "${major}.${minor}.${Number(patch) + 1}"`
	);

	// Update date
	content = content.replace(/CATALOG_LAST_UPDATED\s*=\s*"[^"]+"/, `CATALOG_LAST_UPDATED = "${today}"`);

	return content;
}
